# Generated by Django 3.2.18 on 2023-03-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=100)),
                ('catalogNumber', models.CharField(default='', max_length=100)),
                ('classSection', models.CharField(default='', max_length=100)),
                ('classNumber', models.CharField(default='', max_length=100)),
                ('className', models.CharField(default='', max_length=100)),
                ('instructor', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pronouns', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('fun_fact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tstudentID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pronouns', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('fun_fact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TutorTime',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('tstudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.classes')),
                ('tstudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='SessionBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.tutortime')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.student')),
                ('tstudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.tutor')),
            ],
        ),
    ]
