# Generated by Django 4.1.6 on 2023-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(blank=True, max_length=100, null=True)),
                ('tutorID', models.CharField(blank=True, max_length=100, null=True)),
                ('startTime', models.CharField(blank=True, max_length=100, null=True)),
                ('endTime', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
