# Generated by Django 3.2.18 on 2023-03-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='classID',
        ),
        migrations.AlterField(
            model_name='classes',
            name='catalogNumber',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
