# Generated by Django 4.1.6 on 2023-02-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='catalogNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classes',
            name='classNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classes',
            name='classSection',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classes',
            name='instructor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='className',
            field=models.CharField(default='', max_length=100),
        ),
    ]
