# Generated by Django 4.1.6 on 2023-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
