# Generated by Django 4.1.6 on 2023-02-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_classes_catalognumber_classes_classnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='instructor',
            field=models.CharField(default='', max_length=200),
        ),
    ]
