# Generated by Django 3.2.18 on 2023-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_tutordb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordb',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
