# Generated by Django 4.1.6 on 2023-03-21 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_alter_classes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
