# Generated by Django 4.1.6 on 2023-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_tutor_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.CharField(max_length=10),
        ),
    ]
