# Generated by Django 4.1.6 on 2023-03-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_classes_user_alter_profile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutor_or_student',
            field=models.CharField(default='tutor', max_length=100),
        ),
    ]
