# Generated by Django 3.2.18 on 2023-03-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_tutordb_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='classes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.classes'),
        ),
    ]
