# Generated by Django 4.1.6 on 2023-03-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_profile_tutor_or_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_tutor',
        ),
    ]
