# Generated by Django 4.1.6 on 2023-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_registered',
        ),
    ]
