# Generated by Django 4.1.6 on 2023-03-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_profile_is_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=200)),
                ('hourlyRate', models.FloatField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorclasses',
            name='classID',
        ),
        migrations.RemoveField(
            model_name='tutorclasses',
            name='tstudentID',
        ),
        migrations.RemoveField(
            model_name='tutortime',
            name='tstudentID',
        ),
        migrations.DeleteModel(
            name='SessionBooked',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='TutorClasses',
        ),
        migrations.DeleteModel(
            name='TutorTime',
        ),
    ]
