# Generated by Django 4.1.6 on 2023-03-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_tutorprofile_remove_tutorclasses_classid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='hourlyRate',
            new_name='hourly_rate',
        ),
    ]
