# Generated by Django 4.1.6 on 2023-03-13 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0007_rename_hourlyrate_tutorprofile_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='user',
            field=models.OneToOneField(default='sdb9jg', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
