# Generated by Django 4.1.6 on 2023-03-13 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0008_remove_tutorprofile_profile_tutorprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='user',
            field=models.OneToOneField(default='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
