# Generated by Django 4.1.6 on 2023-03-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_tutorprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
