# Generated by Django 4.1.6 on 2023-03-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_tutorsettings_delete_tutorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorSettings',
        ),
    ]
