# Generated by Django 4.1.6 on 2023-03-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_tutorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
