# Generated by Django 4.1.6 on 2023-03-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_profile2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='is_tutor',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='major',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='pronouns',
        ),
    ]
