# Generated by Django 4.1.6 on 2023-03-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_remove_profile2_email_remove_profile2_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile2',
            old_name='year',
            new_name='hourly_rate',
        ),
    ]
