# Generated by Django 4.1.6 on 2023-03-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_rename_year_profile2_hourly_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile2',
            old_name='fun_fact',
            new_name='classes',
        ),
    ]
