# Generated by Django 4.1.6 on 2023-03-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_rename_fun_fact_profile2_classes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
