# Generated by Django 4.1.6 on 2023-03-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_tutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
